### ISSUE TITLE
plans to update this?

### ISSUE THREAD

**Issue by the-nance** [aswinnnn/weheartpy#1]
Do you have any plans to update this/convert it to js as well?

**Comment by aswinnnn** [comment]
Hey, I apologize for the late reply but yes, I do plan on refactoring a lot of the code and hopefully change the way a lot of the operations work (almost after a year, lol)

I'm not sure if i have plans to convert this into js, I'm not that experienced in JavaScript but i always welcome pull requests to support the functionality and maybe add it to `npm` 

Also, sorry for the huge delay in commenting on this issue as I didn't happen to recieve any notifs on it.

**Comment by aswinnnn** [comment]
weheartpy has been successfully refactored and updated, thanks for opening the issue. Going back to the previous concern about porting it to JavaScript and npm, I feel like that's an idea I should consider when I have time for it and when I'm experienced with JS. It is definitely in my mind though.
