### ISSUE TITLE
Why you using website of weheartit for requests?

### ISSUE THREAD

**Issue by zeviel** [aswinnnn/weheartpy#3]
Why you using website of weheartit for requests? when offical mobile app of [weheartit](https://play.google.com/store/apps/details?id=com.weheartit) have an api for requests -> api.weheartit.com

**Comment by aswinnnn** [comment]
The app's API requires account authentication to request and receive weheartit objects, as far as I know. This API client is provided for people who do not wanna authenticate with an account before proceeding to receive things from weheartit. (Though I understand there's some limitations on the number of objects you can receive, not a bad trade off).

I would be interested in making a wrapper out of their app's API but I'm not sure how the authentication works entirely. if you could find out about the authentication I'd be more than happy to do something with it, would be a huge improvement for the project.

**Comment by zeviel** [comment]
> The app's API requires account authentication to request and receive weheartit objects, as far as I know. This API client is provided for people who do not wanna authenticate with an account before proceeding to receive things from weheartit. (Though I understand there's some limitations on the number of objects you can receive, not a bad trade off).
> 
> I would be interested in making a wrapper out of their app's API but I'm not sure how the authentication works entirely. if you could find out about the authentication I'd be more than happy to do something with it, would be a huge improvement for the project.

Here i made a simple login function that uses the api of application
i captured the request that app makes for login with tool

```python
class WeHeartIt:
    def __init__(self):
        self.api = "https://api.weheartit.com"
        self.headers = {
            "user-agent": "okhttp/3.14.9",
            "x-weheartit-client": "os: 'Android', sdkVersion: '25', device: 'ASUS_Z01QD', appVersion: '9.0.1.RC-GP-Free(21892) (21892)'"
        }

    def login(self, username: str, password: str):
        data = {
            "username": username,
            "password": password,
            "signature": "af3fc56e9223a0f327cac372cd56225b",
            "grant_type": "password"
        }
        response = requests.post(
            f"{self.api}/oauth/token",
            data=data,
            headers=self.headers).json()
        if "access_token" in response:
            self.access_token = response["access_token"]
            self.headers["authorization"] = f"Bearer {self.access_token}"
        return response
```

you can use it like this
```python
weheartit = WeHeartIt()
weheartit.login(username="", password="")
```

**Comment by aswinnnn** [comment]
That seems really interesting. I will definitely add that and work on bringing in new features and improving the codebase, hopefully moving away from the website and using `BeautifulSoup` itself.

Would you like to fork the repo and open a pull request with the changes? I think it'll give you the credits you deserve because this method looks very promising and I didnt even think of it before.

**Comment by aswinnnn** [comment]
> That seems really interesting. I will definitely add that and work on bringing in new features and improving the codebase, hopefully moving away from the website and stop using `BeautifulSoup`. Would you like to fork the repo and open a pull request with the changes? I think it'll give you the credits you deserve because this method looks very promising and I didnt even think of it before.

I've made a branch where I'll be implementing this for now. I'll be populating it with new code every now and then. What tool did you use to capture the app requests? I'm looking to use it for capturing other requests for the API

**Comment by zeviel** [comment]
> > That seems really interesting. I will definitely add that and work on bringing in new features and improving the codebase, hopefully moving away from the website and stop using `BeautifulSoup`. Would you like to fork the repo and open a pull request with the changes? I think it'll give you the credits you deserve because this method looks very promising and I didnt even think of it before.
> 
> I've made a branch where I'll be implementing this for now. I'll be populating it with new code every now and then. What tool did you use to capture the app requests? I'm looking to use it for capturing other requests for the API

can you send me your telegram or discord
i will write

**Comment by aswinnnn** [comment]
> > > That seems really interesting. I will definitely add that and work on bringing in new features and improving the codebase, hopefully moving away from the website and stop using `BeautifulSoup`. Would you like to fork the repo and open a pull request with the changes? I think it'll give you the credits you deserve because this method looks very promising and I didnt even think of it before.
> > 
> > 
> > I've made a branch where I'll be implementing this for now. I'll be populating it with new code every now and then. What tool did you use to capture the app requests? I'm looking to use it for capturing other requests for the API
> 
> can you send me your telegram or discord i will write

Sure, here's my discord ID, `goldy.#5911`

**Comment by aswinnnn** [comment]
I've made a [github repo](https://github.com/aswinnnn/weheartit-api/tree/main) where I've listed all the API endpoints I enumerated from the latest version of the app. Hoping to test most of them with the right data soon.

**Comment by zeviel** [comment]
> I've made a [github repo](https://github.com/aswinnnn/weheartit-api/tree/main) where I've listed all the API endpoints I enumerated from the latest version of the app. Hoping to test most of them with the right data soon.

i sent friend request `sazerac#1516`

**Comment by aswinnnn** [comment]
Update: due to the complications of replicating oauth access this improvement might take some time, but it's definitely something weheartpy would like to achieve. Closing the issue for now, a new branch will be created when its time to implement these features.
